marks = [] #Empty List

# m1 = input("Enter Marks here: ")
# marks.append(m1)   
# m2 = input("Enter Marks here: ")
# marks.append(m2)   
# m3 = input("Enter Marks here: ")
# marks.append(m3)   
# m4 = input("Enter Marks here: ")
# marks.append(m4)   
# m5 = input("Enter Marks here: ")
# marks.append(m5)   
# m6 = input("Enter Marks here: ")
# marks.append(m6)   

f1 = int(input("Enter Marks here: "))
marks.append(f1)   
f2 = int(input("Enter Marks here: "))
marks.append(f2) 
f3 = int(input("Enter Marks here: "))
marks.append(f3)
f4 = int(input("Enter Marks here: "))
marks.append(f4)
f5 = int(input("Enter Marks here: "))
marks.append(f5)
f6 = int(input("Enter Marks here: "))
marks.append(f6)

marks.sort()

print(marks)                